import type { ReplayFrame } from '../types'

/** Fill missing fields when API returns a partial/legacy frame payload. */
export function normalizeFrame(raw: Partial<ReplayFrame> | null | undefined): ReplayFrame | null {
  if (!raw) return null

  return {
    timestamp: raw.timestamp ?? 0,
    frame_index: raw.frame_index ?? 0,
    total_frames: raw.total_frames ?? 1,
    playing: raw.playing ?? false,
    playback_speed: raw.playback_speed ?? 1,
    mode: raw.mode ?? 'REPLAY',
    exchange: raw.exchange ?? 'LOBSTER Replay',
    symbol: raw.symbol ?? 'SIM',
    strategy: raw.strategy ?? 'avellaneda_stoikov',
    regime: raw.regime ?? 'normal',
    system_status: raw.system_status ?? 'healthy',
    best_bid: raw.best_bid ?? null,
    best_ask: raw.best_ask ?? null,
    mid_price: raw.mid_price ?? null,
    spread: raw.spread ?? null,
    reservation_price: raw.reservation_price ?? null,
    fair_value: raw.fair_value ?? null,
    our_bid: raw.our_bid ?? null,
    our_ask: raw.our_ask ?? null,
    bid_depth: raw.bid_depth ?? [],
    ask_depth: raw.ask_depth ?? [],
    position: raw.position ?? 0,
    avg_abs_inventory: raw.avg_abs_inventory ?? 0,
    max_abs_inventory: raw.max_abs_inventory ?? 0,
    exposure: raw.exposure ?? 0,
    risk_score: raw.risk_score ?? 0,
    gamma: raw.gamma ?? 0.1,
    k: raw.k ?? 1.5,
    sigma: raw.sigma ?? 0.02,
    tau: raw.tau ?? 0,
    toxicity: raw.toxicity ?? 0,
    optimal_spread: raw.optimal_spread ?? null,
    kill_switch: raw.kill_switch ?? false,
    circuit_breaker: raw.circuit_breaker ?? false,
    total_pnl: raw.total_pnl ?? 0,
    realized_pnl: raw.realized_pnl ?? 0,
    unrealized_pnl: raw.unrealized_pnl ?? 0,
    spread_capture: raw.spread_capture ?? 0,
    inventory_mtm: raw.inventory_mtm ?? 0,
    transaction_fees: raw.transaction_fees ?? 0,
    adverse_selection_cost: raw.adverse_selection_cost ?? 0,
    sharpe_ratio: raw.sharpe_ratio ?? null,
    sortino_ratio: raw.sortino_ratio ?? null,
    max_drawdown: raw.max_drawdown ?? 0,
    fill_rate: raw.fill_rate ?? 0,
    win_rate: raw.win_rate ?? 0,
    avg_trade_profit: raw.avg_trade_profit ?? 0,
    fill_count: raw.fill_count ?? 0,
    pnl_timeline: raw.pnl_timeline ?? [],
    inventory_timeline: raw.inventory_timeline ?? [],
    quote_trail: raw.quote_trail ?? [],
    recent_fills: raw.recent_fills ?? [],
    queue_position_bid: raw.queue_position_bid ?? null,
    queue_position_ask: raw.queue_position_ask ?? null,
    fill_probability_bid: raw.fill_probability_bid ?? 0,
    fill_probability_ask: raw.fill_probability_ask ?? 0,
    execution_latency_us: raw.execution_latency_us ?? 0,
    quote_lifetime_ms: raw.quote_lifetime_ms ?? 0,
    cancel_rate: raw.cancel_rate ?? 0,
    fill_efficiency: raw.fill_efficiency ?? 0,
    events_per_sec: raw.events_per_sec ?? 0,
    end_to_end_latency_ms: raw.end_to_end_latency_ms ?? 0,
    cpu_percent: raw.cpu_percent ?? 0,
    memory_mb: raw.memory_mb ?? 0,
    order_flow_imbalance: raw.order_flow_imbalance ?? 0,
    events: raw.events ?? [],
    feed_type: raw.feed_type ?? 'historical_replay',
    dataset_name: raw.dataset_name ?? '',
    total_events: raw.total_events ?? 0,
    replay_time_display: raw.replay_time_display ?? '00:00:00.000',
    progress_pct: raw.progress_pct ?? 0,
    live_mode: raw.live_mode ?? false,
    live_connected: raw.live_connected ?? false,
    live_ping_ms: raw.live_ping_ms ?? 0,
    connection_quality: raw.connection_quality ?? 'unknown',
    packet_loss_pct: raw.packet_loss_pct ?? 0,
    book_ladder: raw.book_ladder ?? [],
    quote_decision: raw.quote_decision ?? {
      mid_price: null,
      reservation_price: null,
      fair_value: null,
      inventory: 0,
      volatility: 0,
      gamma: 0.1,
      k: 1.5,
      optimal_half_spread: null,
      optimal_bid: null,
      optimal_ask: null,
      regime: 'normal',
      reasoning: [],
      fill_probability_bid: 0,
      fill_probability_ask: 0,
    },
    pnl_decomposition: raw.pnl_decomposition ?? {
      realized_pnl: 0,
      unrealized_pnl: 0,
      spread_capture: 0,
      inventory_loss: 0,
      transaction_fees: 0,
      slippage: 0,
      adverse_selection: 0,
      net_pnl: 0,
    },
    strategy_comparison: raw.strategy_comparison ?? [],
    latency_breakdown: raw.latency_breakdown ?? {},
    inventory_distribution: raw.inventory_distribution ?? [],
    inventory_heatmap: raw.inventory_heatmap ?? [],
    queue_analytics: raw.queue_analytics ?? {
      bid_position: null,
      ask_position: null,
      bid_queue_length: 0,
      ask_queue_length: 0,
      fill_probability_bid: 0,
      fill_probability_ask: 0,
      expected_time_to_fill_bid_ms: 0,
      expected_time_to_fill_ask_ms: 0,
      queue_movement: 'static',
    },
    calmar_ratio: raw.calmar_ratio ?? null,
    profit_factor: raw.profit_factor ?? 0,
    expectancy: raw.expectancy ?? 0,
    rolling_sharpe: raw.rolling_sharpe ?? [],
    event_inspector: raw.event_inspector ?? {},
    ai_summary: raw.ai_summary ?? '',
    bookmarks: raw.bookmarks ?? [],
    replay_complete:
      raw.replay_complete ??
      ((raw.frame_index ?? 0) >= (raw.total_frames ?? 1) - 1 && !(raw.playing ?? false)),
    algo_state: raw.algo_state,
    asset_class: raw.asset_class,
  }
}